services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - orderbox-net

  reverse-proxy:
    image: nginx:stable
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./html/static:/usr/share/nginx/html/static:ro
    depends_on:
      - wordpress
      - websocket
    networks:
      - orderbox-net

  websocket:
    build: ./websocket
    container_name: websocket
    ports:
      - "8081:8080"
    networks:
      - orderbox-net

  wordpress:
    build: .
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress
      SITE_URL: http://orderbox.local
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
    networks:
      - orderbox-net

volumes:
  db_data:
  wp-content:

networks:
  orderbox-net:
    driver: bridge